/**
 * @homeops/api-client — generated react-query hooks over a shared fetch mutator.
 *
 * Hooks + DTOs are generated by orval from `openapi.snapshot.json` (run `pnpm codegen`).
 * The infra around them is hand-owned and stable: `config` (transport seam), `token-store`
 * (in-memory access token), `http` (base URL + 401-refresh), and `session` (token-persisting
 * MutationCache). One source of truth → no manual web/mobile drift (spec §5.5/§5.9).
 */

export * from './config';
export * from './token-store';
export * from './http';
export * from './session';

// Generated typed hooks (tags-split). Auth + TOTP, household/invitation ("default"), health.
export * from './generated/auth/auth';
export * from './generated/default/default';
export * from './generated/system/system';
